/*
-----------------------------------------------------------------------------
Filename:    OgreApp.cpp
-----------------------------------------------------------------------------


This source file is generated by the
   ___                   _              __    __ _                  _ 
  /___\__ _ _ __ ___    /_\  _ __  _ __/ / /\ \ (_)______ _ _ __ __| |
 //  // _` | '__/ _ \  //_\\| '_ \| '_ \ \/  \/ / |_  / _` | '__/ _` |
/ \_// (_| | | |  __/ /  _  \ |_) | |_) \  /\  /| |/ / (_| | | | (_| |
\___/ \__, |_|  \___| \_/ \_/ .__/| .__/ \/  \/ |_/___\__,_|_|  \__,_|
      |___/                 |_|   |_|                                 
      Ogre 1.7.x Application Wizard for VC10 (July 2011)
      http://code.google.com/p/ogreappwizards/
-----------------------------------------------------------------------------
*/

#include "OgreApp.h"

//-------------------------------------------------------------------------------------
OgreApp::OgreApp(void)
{
}
//-------------------------------------------------------------------------------------
OgreApp::~OgreApp(void)
{
}

//-------------------------------------------------------------------------------------
//void OgreApp::createScene(void)
//{
//    Ogre::Entity* ogreHead = mSceneMgr->createEntity("Head", "ninja.mesh");
//
//    Ogre::SceneNode* headNode = mSceneMgr->getRootSceneNode()->createChildSceneNode();
//	headNode->setPosition(0,-10,-0.5);
//    headNode->attachObject(ogreHead);
//
//    // Set ambient light
//    mSceneMgr->setAmbientLight(Ogre::ColourValue(0.5, 0.5, 0.5));
//
//    // Create a light
//    Ogre::Light* l = mSceneMgr->createLight("MainLight");
//    l->setPosition(20,80,50);
//
//	Ogre::Plane plane(Ogre::Vector3::UNIT_Y,-10);
//
//	Ogre::MeshManager::getSingleton().createPlane("plane",Ogre::ResourceGroupManager::DEFAULT_RESOURCE_GROUP_NAME,plane,
//		1500,1500,200,200,true,1,5,5,Ogre::Vector3::UNIT_Z);
//
//	Ogre::Entity* ent= mSceneMgr->createEntity("LightPlaneEntity","plane");
//
//	mSceneMgr->getRootSceneNode()->createChildSceneNode()->attachObject(ent);
//
//	ent->setMaterialName("Examples/BeachStones");
//
//	Ogre::Light* light2= mSceneMgr->createLight("Light2");
//
//	light2->setType(Ogre::Light::LT_DIRECTIONAL);
//
//	light2->setDirection(Ogre::Vector3(1,-1,0));
//
//}



#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
#define WIN32_LEAN_AND_MEAN
#include "windows.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif

#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
    INT WINAPI WinMain( HINSTANCE hInst, HINSTANCE, LPSTR strCmdLine, INT )
#else
    int main(int argc, char *argv[])
#endif
    {
        // Create application object
        OgreApp app;

        try {
            app.go();
        } catch( Ogre::Exception& e ) {
#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
            MessageBox( NULL, e.getFullDescription().c_str(), "An exception has occured!", MB_OK | MB_ICONERROR | MB_TASKMODAL);
#else
            std::cerr << "An exception has occured: " <<
                e.getFullDescription().c_str() << std::endl;
#endif
        }

        return 0;
    }

#ifdef __cplusplus
}
#endif
